[package]
name = "autd3-modulation-audio-file"
version = "21.0.0-alpha.0"
authors = ["shun suzuki <suzuki@hapis.k.u-tokyo.ac.jp>"]
edition = "2021"

license = "MIT"
description = "AUTD library for Rust."
repository = "https://github.com/shinolab/autd3-rs"
readme = "README.md"
keywords = ["autd"]

[dependencies]
hound = "3.5.0"
autd3-driver = { path = "../autd3-driver", version = "21.0.0-alpha.0", default-features = false, features = ["derive"] }
wav_io = "0.1.8"
thiserror = "1.0.40"

[features]
default = ["rpitit"]
single_float = ["autd3-driver/single_float"]
rpitit = ["autd3-driver/rpitit"]
async-trait = ["autd3-driver/async-trait"]
