[package]
name = "autd3-modulation-audio-file"
version = "26.0.0-alpha.0"
authors = ["shun suzuki <suzuki@hapis.k.u-tokyo.ac.jp>"]
edition = "2021"

license = "MIT"
description = "AUTD library for Rust."
repository = "https://github.com/shinolab/autd3-rs"
readme = "README.md"
keywords = ["autd"]

[dependencies]
hound = { workspace = true }
autd3-driver = { path = "../autd3-driver", version = "26.0.0-alpha.0" }
thiserror = { workspace = true }
csv = "1.3.0"

[features]
default = []
async-trait = ["autd3-driver/async-trait"]

[dev-dependencies]
anyhow = { workspace = true }
tempfile = { workspace = true }
rstest = { workspace = true }
