[package]
name = "autd3-derive"
version = "23.0.0-rc.0"
authors = ["shun suzuki <suzuki@hapis.k.u-tokyo.ac.jp>"]
edition = "2021"

license = "MIT"
description = "Wav Modulation for AUTD."
repository = "https://github.com/shinolab/autd3-rs"
readme = "README.md"
keywords = ["autd"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
proc-macro = true

[dependencies]
proc-macro2 = { workspace = true }
quote = { workspace = true }
syn = { workspace = true, features = ["full"] }

[features]
default = []
