mod completion_steps;
mod update_rate;

const SILNCER_MODE_FIXED_COMPLETION_STEPS: u8 = 0;
const SILNCER_MODE_FIXED_UPDATE_RATE: u8 = 1;
const SILENCER_MODE_BIT: u8 = 0;
const SILENCER_CTL_FLAG_STRICT_MODE_BIT: u8 = 1;

const SILENCER_CTL_FLAG_MODE: u8 = 1 << SILENCER_MODE_BIT;
const SILENCER_CTL_FLAG_FIXED_COMPLETION_STEPS: u8 =
    SILENCER_CTL_FLAG_MODE & SILNCER_MODE_FIXED_COMPLETION_STEPS;
const SILENCER_CTL_FLAG_FIXED_UPDATE_RATE: u8 =
    SILENCER_CTL_FLAG_MODE & SILNCER_MODE_FIXED_UPDATE_RATE;
const SILENCER_CTL_FLAG_STRICT_MODE: u8 = 1 << SILENCER_CTL_FLAG_STRICT_MODE_BIT;

pub use completion_steps::ConfigSilencerFixedCompletionStepsOp;
pub use update_rate::ConfigSilencerFixedUpdateRateOp;
