[package]
name = "autd3-protobuf"
version = "26.0.0"
authors = ["shun suzuki <suzuki@hapis.k.u-tokyo.ac.jp>"]
edition = "2021"

license = "MIT"
description = "Protocol Buffer"
repository = "https://github.com/shinolab/autd3-rs"
readme = "README.md"
keywords = ["autd"]

[dependencies]
prost = { workspace = true }
tonic = { workspace = true, features = ["prost", "codegen", "transport"] }
autd3-driver = { path = "../autd3-driver", version = "26.0.0" }
autd3 = { path = "../autd3", version = "26.0.0", optional = true }
autd3-gain-holo = { path = "../autd3-gain-holo", version = "26.0.0", optional = true }
thiserror = { workspace = true }
tokio = { workspace = true, features = ["sync"], optional = true }
seq-macro = { version = "0.3.5", optional = true }

[build-dependencies]
tonic-build = { workspace = true, optional = true }

[features]
default = []
tonic-build = ["dep:tonic-build"]
lightweight = ["tokio", "seq-macro", "autd3", "autd3-gain-holo", "autd3-driver/derive", "async-trait"]
async-trait = ["autd3-driver/async-trait", "autd3/async-trait", "autd3-gain-holo/async-trait"]

[dev-dependencies]
assert_approx_eq = { workspace = true }
rand = { workspace = true }
rstest = { workspace = true }
