[package]
name = "autd3-protobuf"
version = "21.0.0-alpha.0"
authors = ["shun suzuki <suzuki@hapis.k.u-tokyo.ac.jp>"]
edition = "2021"

license = "MIT"
description = "Protocol Buffer"
repository = "https://github.com/shinolab/autd3-rs"
readme = "README.md"
keywords = ["autd"]

[dependencies]
h2 = "0.4.0"
prost = { version = "0.12.0" }
tonic = { version = "0.10.0", default-features = false, features = ["prost", "codegen", "transport"] }
autd3-driver = { path = "../autd3-driver", version = "21.0.0-alpha.0", default-features = false }
thiserror = "1.0.40"

[build-dependencies]
tonic-build = "0.10.0"

[features]
rpitit = ["autd3-driver/rpitit"]
async-trait = ["autd3-driver/async-trait"]
