[package]
name = "autd3-protobuf"
description = "gRPC protobuf for autd3"
readme = "README.md"
keywords = { workspace = true }
version = { workspace = true }
authors = { workspace = true }
edition = { workspace = true }
license = { workspace = true }
repository = { workspace = true }

[dependencies]
prost = { workspace = true }
tonic = { workspace = true, features = ["channel", "codegen", "prost", "server"] }
autd3-driver = { workspace = true }
autd3 = { workspace = true, optional = true }
autd3-gain-holo = { workspace = true, optional = true }
thiserror = { workspace = true }
tokio = { workspace = true, optional = true }
seq-macro = { workspace = true, optional = true }
zerocopy = { workspace = true }

[build-dependencies]
tonic-build = { workspace = true, optional = true }

[features]
default = []
tonic-build = ["dep:tonic-build"]
lightweight = ["tokio", "seq-macro", "autd3", "autd3-gain-holo", "autd3-driver/derive", "autd3-driver/lightweight", "async-trait"]
async-trait = ["autd3-driver/async-trait", "autd3/async-trait", "autd3-gain-holo/async-trait"]

[dev-dependencies]
approx = { workspace = true }
rand = { workspace = true }
rstest = { workspace = true }
