[package]
name = "autd3-core"
description = "AUTD3 core traits and types"
readme = "README.md"
keywords = { workspace = true }
version = { workspace = true }
authors = { workspace = true }
edition = { workspace = true }
license = { workspace = true }
repository = { workspace = true }

[package.metadata.docs.rs]
all-features = true
rustdoc-args = ["--cfg", "docsrs"]

[features]
acoustics = ["common", "geometry"]
async = ["tokio"]
async-trait = ["async", "dep:async-trait"]
datagram = ["common", "geometry", "ethercat", "smallvec", "num", "environment"]
common = ["derive_more", "derive_more/add", "derive_more/mul", "derive_more/debug"]
derive = ["autd3-derive", "tynm", "num_cpus"]
ethercat = ["time", "thiserror"]
gain = ["common", "datagram", "geometry", "thiserror", "bit-vec", "zerocopy", "derive_more", "derive_more/display", "environment"]
geometry = ["nalgebra", "bvh", "paste", "getset", "common", "derive_more", "derive_more/add", "derive_more/mul", "derive_more/into_iterator", "derive_more/deref", "derive_more/debug"]
left_handed = []
link = ["bitfield-struct", "zerocopy", "getset", "ethercat", "datagram", "geometry", "derive_more", "derive_more/display"]
modulation = ["getset", "sampling_config", "utils", "common", "datagram", "derive_more", "derive_more/display"]
sampling_config = ["common", "thiserror", "utils"]
use_meter = []
utils = []
sleep = ["spin_sleep"]
environment = []

[dependencies]
async-trait = { workspace = true, optional = true }
autd3-derive = { workspace = true, optional = true }
bit-vec = { workspace = true, optional = true }
bitfield-struct = { workspace = true, optional = true }
bvh = { workspace = true, optional = true }
derive_more = { workspace = true, optional = true }
getset = { workspace = true, optional = true }
nalgebra = { workspace = true, optional = true }
num = { workspace = true, optional = true }
num_cpus = { workspace = true, optional = true }
paste = { workspace = true, optional = true }
smallvec = { workspace = true, optional = true }
spin_sleep = { workspace = true, optional = true }
thiserror = { workspace = true, optional = true }
time = { workspace = true, optional = true, features = ["macros", "std"] }
tokio = { workspace = true, optional = true, features = ["time", "rt"] }
tynm = { workspace = true, optional = true }
zerocopy = { workspace = true, optional = true, features = ["derive"] }

[dev-dependencies]
anyhow = { workspace = true }
approx = { workspace = true }
itertools = { workspace = true }
rand = { workspace = true, features = ["thread_rng"] }
rstest = { workspace = true }
