[package]
name = "autd3-core"
description = "AUTD3 core traits and types"
readme = "README.md"
keywords = { workspace = true }
version = { workspace = true }
authors = { workspace = true }
edition = { workspace = true }
license = { workspace = true }
repository = { workspace = true }

[package.metadata.docs.rs]
all-features = true
rustdoc-args = ["--cfg", "docsrs"]

[features]
std = ["time/std", "spin_sleep"]
default = []
firmware = ["common", "ethercat", "thiserror", "utils", "zerocopy", "num-traits"]
acoustics = ["common", "geometry", "num-complex", "num-traits"]
async = ["tokio"]
datagram = ["common", "firmware", "geometry", "ethercat", "smallvec", "environment"]
common = []
derive = ["autd3-derive"]
ethercat = ["time", "thiserror"]
gain = ["common", "datagram", "geometry", "thiserror", "bit-vec", "environment", "firmware"]
geometry = ["nalgebra", "simba", "pastey", "common"]
left_handed = []
link = ["bitfield-struct", "zerocopy", "ethercat", "datagram", "geometry"]
modulation = ["firmware", "utils", "common", "datagram"]
use_meter = []
utils = ["num-traits"]
sleep = []
environment = ["num-traits"]

[dependencies]
autd3-derive = { workspace = true, optional = true }
bit-vec = { workspace = true, optional = true }
bitfield-struct = { workspace = true, optional = true }
nalgebra = { workspace = true, optional = true }
pastey = { workspace = true, optional = true }
smallvec = { workspace = true, optional = true }
spin_sleep = { workspace = true, optional = true }
thiserror = { workspace = true, optional = true }
time = { workspace = true, optional = true, features = ["macros"] }
tokio = { workspace = true, optional = true, features = ["time", "rt"] }
zerocopy = { workspace = true, optional = true, features = ["derive"] }
simba = { workspace = true, optional = true, features = ["libm"] }
num-complex = { workspace = true, optional = true, features = ["libm"] }
num-traits = { workspace = true, features = ["libm"], optional = true }

[dev-dependencies]
approx = { workspace = true }
itertools = { workspace = true }
rand = { workspace = true, features = ["thread_rng"] }
rstest = { workspace = true }
