[package]
name = "autd3"
description = "AUTD3 library"
readme = "README.md"
keywords = { workspace = true }
version = { workspace = true }
authors = { workspace = true }
edition = { workspace = true }
license = { workspace = true }
repository = { workspace = true }

[dependencies]
autd3-firmware-emulator = { workspace = true }
autd3-core = { workspace = true, features = ["link", "derive", "gain", "modulation", "resampler"] }
autd3-driver = { workspace = true }
autd3-derive = { workspace = true }
num = { workspace = true }
thiserror = { workspace = true }
tokio = { workspace = true, features = ["time", "rt-multi-thread"], optional = true }
derive_more = { workspace = true }
tynm = { workspace = true }
itertools = { workspace = true }
tracing = { workspace = true }
bit-vec = { workspace = true }
rayon = { workspace = true }
derive-new = { workspace = true }
zerocopy = { workspace = true }
spin_sleep = { workspace = true }

[target.'cfg(windows)'.dependencies]
windows = { workspace = true, features = ["Win32_Security"] }

[features]
default = []
async = ["tokio", "autd3-core/async"]
async-trait = ["async", "autd3-core/async-trait"]
dynamic_freq = ["autd3-driver/dynamic_freq", "autd3-firmware-emulator/dynamic_freq"]

[dev-dependencies]
rand = { workspace = true }
tokio = { workspace = true, features = ["macros", "rt"] }
anyhow = { workspace = true }
rstest = { workspace = true }
tokio-test = { workspace = true }

[package.metadata.docs.rs]
features = ["async"]
rustdoc-args = ["--cfg", "docsrs"]
