[package]
name = "autd3"
description = "AUTD3 library"
readme = "README.md"
keywords = { workspace = true }
version = { workspace = true }
authors = { workspace = true }
edition = { workspace = true }
license = { workspace = true }
repository = { workspace = true }

[package.metadata.docs.rs]
features = ["async"]
rustdoc-args = ["--cfg", "docsrs"]

[features]
default = []
async = ["tokio", "autd3-core/async"]
async-trait = ["async", "autd3-core/async-trait"]

[dependencies]
autd3-core = { workspace = true, features = ["link", "derive", "gain", "modulation"] }
autd3-derive = { workspace = true }
autd3-driver = { workspace = true }
autd3-firmware-emulator = { workspace = true }
bit-vec = { workspace = true }
derive_more = { workspace = true }
getset = { workspace = true }
itertools = { workspace = true }
num = { workspace = true }
spin_sleep = { workspace = true }
thiserror = { workspace = true }
tokio = { workspace = true, features = ["time", "rt-multi-thread"], optional = true }
tracing = { workspace = true }
zerocopy = { workspace = true }

[dev-dependencies]
anyhow = { workspace = true }
criterion = { workspace = true }
rand = { workspace = true, features = ["thread_rng"] }
rstest = { workspace = true }
tokio = { workspace = true, features = ["macros", "rt"] }
tokio-test = { workspace = true }

[target.'cfg(windows)'.dependencies]
windows = { workspace = true, features = ["Win32_Security"] }

[lib]
bench = false

[[bench]]
name = "autd3-group"
path = "benches/group.rs"
harness = false
