[package]
name = "autd3"
description = "AUTD3 library"
readme = "README.md"
keywords = { workspace = true }
version = { workspace = true }
authors = { workspace = true }
edition = { workspace = true }
license = { workspace = true }
repository = { workspace = true }

[package.metadata.docs.rs]
features = ["async"]
rustdoc-args = ["--cfg", "docsrs"]

[features]
default = []
async = ["tokio", "autd3-core/async", "autd3-driver/async"]
async-trait = ["async", "autd3-core/async-trait", "autd3-driver/async-trait"]

[dependencies]
autd3-core = { workspace = true, features = ["link", "derive", "gain", "modulation"] }
autd3-driver = { workspace = true }
autd3-firmware-emulator = { workspace = true }
autd3-firmware-emulator-v10 = { version = "=31.0.1", package = "autd3-firmware-emulator" }
autd3-firmware-emulator-v11 = { version = "=33.0.0", package = "autd3-firmware-emulator" }
bit-vec = { workspace = true }
derive_more = { workspace = true }
getset = { workspace = true }
itertools = { workspace = true }
num = { workspace = true }
smallvec = { workspace = true }
tokio = { workspace = true, features = ["time", "rt-multi-thread"], optional = true }
zerocopy = { workspace = true }

[dev-dependencies]
anyhow = { workspace = true }
criterion = { workspace = true }
rand = { workspace = true, features = ["thread_rng"] }
rstest = { workspace = true }
tokio = { workspace = true, features = ["macros", "rt"] }
tokio-test = { workspace = true }

[lib]
bench = false

[[bench]]
name = "autd3-group"
path = "benches/group.rs"
harness = false
