[package]
name = "autd3"
version = "22.0.4"
authors = ["shun suzuki <suzuki@hapis.k.u-tokyo.ac.jp>"]
edition = "2021"

license = "MIT"
description = "AUTD3 library"
repository = "https://github.com/shinolab/autd3-rs"
readme = "README.md"
keywords = ["autd"]

[dependencies]
autd3-driver = { path = "../autd3-driver", version = "22.0.4" }
autd3-firmware-emulator = { path = "../autd3-firmware-emulator", version = "22.0.4", default-features = false }
num = { workspace = true }
thiserror = { workspace = true }
bitvec = { workspace = true }
tokio = { workspace = true, features = ["rt-multi-thread"] }

[features]
default = []
async-trait = ["autd3-driver/async-trait"]

[dev-dependencies]
assert_approx_eq = { workspace = true }
rand = { workspace = true }
criterion = { workspace = true, features = ["html_reports"] }
itertools = { workspace = true }
tokio = { workspace = true, features = ["macros", "rt-multi-thread"] }
anyhow = { workspace = true }

[[bench]]
name = "gain"
path = "benches/gain/primitive.rs"
harness = false
