[package]
name = "autd3-link-simulator"
description = "autd3 link for simulator"
readme = "README.md"
keywords = { workspace = true }
version = { workspace = true }
authors = { workspace = true }
edition = { workspace = true }
license = { workspace = true }
repository = { workspace = true }

[dependencies]
autd3-protobuf = { workspace = true }
autd3-driver = { workspace = true }
tonic = { workspace = true }
tracing = { workspace = true }

[features]
default = []
async-trait = ["autd3-driver/async-trait", "autd3-protobuf/async-trait"]
