[package]
name = "autd3-link-simulator"
version = "22.0.0"
authors = ["shun suzuki <suzuki@hapis.k.u-tokyo.ac.jp>"]
edition = "2021"

license = "MIT"
description = "Link for autd-simulator"
repository = "https://github.com/shinolab/autd3-rs"
readme = "README.md"
keywords = ["autd"]

[dependencies]
autd3-protobuf = { path = "../autd3-protobuf", version = "22.0.0" }
autd3-driver = { path = "../autd3-driver", version = "22.0.0" }
thiserror = "1.0.30"
tonic = "0.11.0"

[features]
default = []
single_float = ["autd3-driver/single_float"]
async-trait = ["autd3-driver/async-trait", "autd3-protobuf/async-trait"]
