[package]
name = "autd3-link-simulator"
description = "Link for autd-simulator"
readme = "README.md"
keywords = ["autd"]
version = { workspace = true }
authors = { workspace = true }
edition = { workspace = true }
license = { workspace = true }
repository = { workspace = true }

[dependencies]
autd3-protobuf = { workspace = true }
autd3-driver = { workspace = true }
thiserror = { workspace = true }
tonic = { workspace = true }

[features]
default = []
async-trait = ["autd3-driver/async-trait", "autd3-protobuf/async-trait"]
capi = ["async-trait"]
