name: 'build tools setup action'
inputs:
  os:
    description: 'os'
    required: true
    default: ''
  arch:
    description: 'arch'
    required: false
    default: ''
  toolchain:
    description: 'toolchain'
    required: false
    default: 'stable'
  components:
    description: 'components'
    required: false
    default: ''
runs:
  using: "composite"
  steps:
    - name: Setup Python
      uses: actions/setup-python@v5
      with:
        python-version: "3.12"
      
    - name: Setup Rust
      uses: actions-rust-lang/setup-rust-toolchain@v1
      with:
        toolchain: ${{ inputs.toolchain }}
        components: ${{ inputs.components }}
    - uses: taiki-e/install-action@v2
      with:
        tool: nextest

    - name: install cross
      shell: bash
      if: inputs.os == 'ubuntu-latest' && inputs.arch
      run: |
        curl -L https://github.com/cross-rs/cross/releases/download/v0.2.5/cross-x86_64-unknown-linux-gnu.tar.gz > cross.tar.gz
        tar -xzf cross.tar.gz
        cp cross /usr/local/bin
        cp cross-util /usr/local/bin
        rm cross.tar.gz

    - name: install aarch64-pc-windows-msvc target
      shell: bash
      if: inputs.os == 'windows-latest' && inputs.arch
      run: |
        rustup target install aarch64-pc-windows-msvc
