name: 'build tools setup action'
inputs:
  toolchain:
    description: 'toolchain'
    required: false
    default: 'stable'
  components:
    description: 'components'
    required: false
    default: ''
runs:
  using: "composite"
  steps:
    - name: setup rust
      uses: actions-rust-lang/setup-rust-toolchain@v1
      with:
        toolchain: ${{ inputs.toolchain }}
        components: ${{ inputs.components }}

    - uses: taiki-e/install-action@v2
      with:
        tool: cargo-make
