name: 'build tools setup action'
inputs:
  github-token:
    description: 'GITHUB_TOKEN'
    required: true
    default: ''
  os:
    description: 'os'
    required: true
    default: ''
  arch:
    description: 'arch'
    required: false
    default: ''
runs:
  using: "composite"
  steps:
    - name: Setup Python
      uses: actions/setup-python@v5
      with:
        python-version: "3.12"
      
    - name: Setup Rust
      uses: actions-rust-lang/setup-rust-toolchain@v1
      with:
        toolchain: stable

    - name: install cross
      shell: bash
      if: inputs.os == 'ubuntu-latest' && inputs.arch
      run: |
        curl -L https://github.com/cross-rs/cross/releases/download/v0.2.5/cross-x86_64-unknown-linux-gnu.tar.gz > cross.tar.gz
        tar -xzf cross.tar.gz
        cp cross /usr/local/bin
        cp cross-util /usr/local/bin
        rm cross.tar.gz
