[package]
name = "autd3-link-soem"
version = "22.0.3"
authors = ["shun suzuki <suzuki@hapis.k.u-tokyo.ac.jp>"]
edition = "2021"

license-file = "LICENSE"
description = "Link of AUTD using SOEM."
repository = "https://github.com/shinolab/autd3-rs"
readme = "README.md"
keywords = ["autd"]

[build-dependencies]
cc = { version = "1.0.73", features = ["parallel"], optional = true }
glob = { version = "0.3.0", optional = true }

[dependencies]
autd3-driver = { path = "../autd3-driver", version = "22.0.3" }
autd3-protobuf = { path = "../autd3-protobuf", version = "22.0.3", optional = true }
thiserror = { version = "1.0.30", optional = true }
time = { version = "0.3.23", default-features = false, features = ["std"], optional = true }
tonic = { version = "0.11.0", optional = true }
tokio = { version = "1.34.0", features = ["time"] }
async-channel = { version = "2.1.1", optional = true }

[target.'cfg(windows)'.dependencies]
windows = { version = "0.54.0", features = ["Win32_Foundation", "Win32_System_Performance", "Win32_Networking_WinSock", "Win32_System_SystemInformation"] }

[features]
local = ["cc", "glob", "async-channel", "time", "thiserror"]
remote = ["autd3-protobuf", "tonic"]
default = ["local"]
all = ["local", "remote"]
async-trait = ["autd3-driver/async-trait", "autd3-protobuf/async-trait"]
