[package]
name = "autd3-firmware-emulator"
version = "25.3.2"
authors = ["shun suzuki <suzuki@hapis.k.u-tokyo.ac.jp>"]
edition = "2021"

license = "MIT"
description = "AUTD3 firmware emulator"
repository = "https://github.com/shinolab/autd3-rs"
readme = "README.md"
keywords = ["autd"]

[dependencies]
autd3-driver = { path = "../autd3-driver", version = "25.3.2" }
time = { workspace = true, features = ["std"] }
num-integer = { workspace = true }
thiserror = { workspace = true }

[dev-dependencies]
anyhow = { workspace = true }
time = { workspace = true, features = ["std", "macros"] }
autd3-derive = { path = "../autd3-derive", version = "25.3.2" }
itertools = { workspace = true }
rand = { workspace = true }
rstest = { workspace = true }

[features]
default = []
capi = ["dynamic_freq", "async-trait"]
async-trait = ["autd3-driver/async-trait"]
dynamic_freq = ["autd3-driver/dynamic_freq"]
test = ["autd3-driver/test"]
