[package]
name = "autd3-firmware-emulator"
description = "AUTD3 firmware emulator"
readme = "README.md"
keywords = ["autd"]
version = { workspace = true }
authors = { workspace = true }
edition = { workspace = true }
license = { workspace = true }
repository = { workspace = true }

[dependencies]
autd3-driver = { workspace = true }
autd3-derive = { workspace = true }
time = { workspace = true, features = ["std"] }
num-integer = { workspace = true }
thiserror = { workspace = true }
derive-new = { workspace = true }
zerocopy = { workspace = true }

[dev-dependencies]
anyhow = { workspace = true }
time = { workspace = true, features = ["std", "macros"] }
autd3-derive = { workspace = true }
itertools = { workspace = true }
rand = { workspace = true }
rstest = { workspace = true }

[features]
default = []
async-trait = ["autd3-driver/async-trait"]
