[package]
name = "autd3-firmware-emulator"
version = "22.0.3"
authors = ["shun suzuki <suzuki@hapis.k.u-tokyo.ac.jp>"]
edition = "2021"

license = "MIT"
description = "AUTD3 firmware emulator"
repository = "https://github.com/shinolab/autd3-rs"
readme = "README.md"
keywords = ["autd"]

[dependencies]
autd3-driver = { path = "../autd3-driver", version = "22.0.3" }
chrono = { workspace = true }
num-integer = { workspace = true }
thiserror = { workspace = true }

[dev-dependencies]
anyhow = { workspace = true }
autd3-derive = { path = "../autd3-derive", version = "22.0.3" }
itertools = { workspace = true }
rand = { workspace = true }

[features]
default = []
async-trait = ["autd3-driver/async-trait"]
