[package]
name = "autd3-driver"
description = "AUTD3 driver"
readme = "README.md"
keywords = ["autd"]
version = { workspace = true }
authors = { workspace = true }
edition = { workspace = true }
license = { workspace = true }
repository = { workspace = true }

[dependencies]
serde = { workspace = true, features = ["derive"], optional = true }
bitflags = { workspace = true }
thiserror = { workspace = true }
nalgebra = { workspace = true, features = ["std"] }
bit-vec = { workspace = true }
time = { workspace = true, features = ["std", "macros"] }
tokio = { workspace = true, features = ["time"] }
autd3-derive = { workspace = true }
async-trait = { workspace = true, optional = true }
num-complex = { workspace = true, features = ["std"] }
rand = { workspace = true, optional = true }
bitfield-struct = { workspace = true }
rayon = { workspace = true }
itertools = { workspace = true }
derive_more = { workspace = true }
tracing = { workspace = true }
tynm = { workspace = true }

[target.'cfg(windows)'.dependencies]
windows = { version = "0.58.0", features = ["Win32_Media_Multimedia", "Win32_System_Threading", "Win32_Foundation"] }

[dev-dependencies]
rand = { workspace = true }
assert_approx_eq = { workspace = true }
serde_json = { workspace = true }
tokio = { workspace = true, features = ["macros", "rt-multi-thread"] }
anyhow = { workspace = true }
rstest = { workspace = true }
criterion.workspace = true

[features]
default = ["derive"]
async-trait = ["dep:async-trait"]
use_meter = []
left_handed = []
serde = ["dep:serde"]
derive = []
capi = ["async-trait"]

[lib]
bench = false

[[bench]]
name = "autd3-driver"
path = "benches/gain.rs"
harness = false
