[package]
name = "autd3-driver"
description = "AUTD3 driver"
readme = "README.md"
keywords = { workspace = true }
version = { workspace = true }
authors = { workspace = true }
edition = { workspace = true }
license = { workspace = true }
repository = { workspace = true }

[dependencies]
autd3-core = { workspace = true, features = ["gain", "geometry", "derive", "link", "ethercat", "modulation"] }
autd3-derive = { workspace = true }
bitfield-struct = { workspace = true }
bitflags = { workspace = true }
derive_more = { workspace = true, features = ["deref_mut"] }
derive-new = { workspace = true }
getset = { workspace = true }
itertools = { workspace = true, features = ["use_alloc"] }
nalgebra = { workspace = true }
rayon = { workspace = true }
seq-macro = { workspace = true }
thiserror = { workspace = true }
time = { workspace = true, features = ["macros", "std"] }
tracing = { workspace = true, features = ["attributes"] }
zerocopy = { workspace = true }

[dev-dependencies]
rand = { workspace = true }
approx = { workspace = true }
anyhow = { workspace = true }
rstest = { workspace = true }
criterion = { workspace = true }

[features]
default = []
lightweight = []
dynamic_freq = ["autd3-core/dynamic_freq"]

[lib]
bench = false

[[bench]]
name = "autd3-driver"
path = "benches/gain.rs"
harness = false

[package.metadata.docs.rs]
features = []
rustdoc-args = ["--cfg", "docsrs"]
