[package]
name = "autd3-driver"
description = "AUTD3 driver"
readme = "README.md"
keywords = { workspace = true }
version = { workspace = true }
authors = { workspace = true }
edition = { workspace = true }
license = { workspace = true }
repository = { workspace = true }

[dependencies]
serde = { workspace = true, optional = true }
bitflags = { workspace = true }
bvh = { workspace = true }
thiserror = { workspace = true }
nalgebra = { workspace = true }
bit-vec = { workspace = true }
time = { workspace = true, features = ["macros", "std"] }
autd3-derive = { workspace = true }
async-trait = { workspace = true, optional = true }
bitfield-struct = { workspace = true }
rayon = { workspace = true }
itertools = { workspace = true }
derive_more = { workspace = true, features = ["add", "debug", "deref", "deref_mut", "display", "into_iterator", "mul"] }
tracing = { workspace = true }
seq-macro = { workspace = true }
derive-new = { workspace = true }
zerocopy = { workspace = true }
paste = { workspace = true }

[target.'cfg(windows)'.dependencies]
windows = { workspace = true, features = ["Win32_Media", "Win32_System_Threading"] }

[dev-dependencies]
rand = { workspace = true }
approx = { workspace = true }
serde_json = { workspace = true }
anyhow = { workspace = true }
rstest = { workspace = true }
criterion = { workspace = true }

[features]
default = ["derive"]
async = []
lightweight = []
async-trait = ["dep:async-trait"]
use_meter = []
left_handed = []
serde = ["dep:serde"]
derive = []
dynamic_freq = []

[lib]
bench = false

[[bench]]
name = "autd3-driver"
path = "benches/gain.rs"
harness = false

[package.metadata.docs.rs]
features = ["lightweight", "async", "serde", "derive"]
rustdoc-args = ["--cfg", "docsrs"]
