[package]
name = "autd3-driver"
version = "23.0.0"
authors = ["shun suzuki <suzuki@hapis.k.u-tokyo.ac.jp>"]
edition = "2021"
license = "MIT"
description = "AUTD3 driver"
repository = "https://github.com/shinolab/autd3-rs"
readme = "README.md"
keywords = ["autd"]

[dependencies]
serde = { workspace = true, features = ["derive"], optional = true }
bitflags = { workspace = true }
thiserror = { workspace = true }
nalgebra = { workspace = true, features = ["std"] }
bitvec = { workspace = true }
time = { workspace = true, features = ["std", "macros"] }
tokio = { workspace = true, features = ["time"] }
autd3-derive = { path = "../autd3-derive", version = "23.0.0" }
async-trait = { workspace = true, optional = true }
num-complex = { workspace = true, features = ["std"] }
rand = { workspace = true, optional = true }
bitfield-struct = { workspace = true }
const_fn = { workspace = true }
rayon = { workspace = true, optional = true }

[target.'cfg(windows)'.dependencies]
windows = { version = "0.56.0", features = ["Win32_Media_Multimedia", "Win32_System_Threading", "Win32_Foundation"] }

[dev-dependencies]
rand = { workspace = true }
assert_approx_eq = { workspace = true }
itertools = { workspace = true }
serde_json = { workspace = true }
tokio = { workspace = true, features = ["macros", "rt-multi-thread"] }
autd3 = { path = "../autd3", version = "23.0.0" }
anyhow = { workspace = true }
rstest = { workspace = true }

[features]
default = ["derive", "rand", "parallel"]
async-trait = ["dep:async-trait"]
parallel = ["rayon"]
use_meter = []
left_handed = []
serde = ["dep:serde"]
derive = []
rand = ["dep:rand"]
variable_freq = []
