[package]
name = "autd3-driver"
description = "AUTD3 driver"
readme = "README.md"
keywords = { workspace = true }
version = { workspace = true }
authors = { workspace = true }
edition = { workspace = true }
license = { workspace = true }
repository = { workspace = true }

[package.metadata.docs.rs]
features = ["async"]
rustdoc-args = ["--cfg", "docsrs"]

[features]
async = ["autd3-core/async"]
async-trait = ["autd3-core/async-trait"]
default = []

[dependencies]
autd3-core = { workspace = true, features = ["gain", "common", "geometry", "derive", "link", "ethercat", "modulation", "sampling_config", "sleep"] }
autd3-derive = { workspace = true }
bitfield-struct = { workspace = true }
bitflags = { workspace = true }
derive_more = { workspace = true, features = ["deref_mut"] }
getset = { workspace = true }
itertools = { workspace = true, features = ["use_alloc"] }
nalgebra = { workspace = true }
num = { workspace = true }
num_cpus = { workspace = true }
paste = { workspace = true }
rayon = { workspace = true }
seq-macro = { workspace = true }
thiserror = { workspace = true }
time = { workspace = true, features = ["macros", "std"] }
tynm = { workspace = true }
zerocopy = { workspace = true }

[dev-dependencies]
anyhow = { workspace = true }
approx = { workspace = true }
criterion = { workspace = true }
rand = { workspace = true, features = ["thread_rng"] }
rstest = { workspace = true }
tokio = { workspace = true, features = ["macros"] }
tokio-test = { version = "0.4.4", default-features = false }

[lib]
bench = false

[[bench]]
name = "autd3-driver-gain"
path = "benches/gain.rs"
harness = false
