name: Coverage

on:
  push:
    branches: [ "main" ]
  pull_request: {}
  merge_group:
    branches: [ "main" ]

env:
  RUSTFLAGS: "-Cinstrument-coverage"
  LLVM_PROFILE_FILE: "target/coverage/%p-%m.profraw"

jobs:
  coverage:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/setup-build
        with:
          os: ubuntu-latest
          components: llvm-tools
      - run: cargo install grcov
      - run: |
          python3 build.py cov
      - uses: codecov/codecov-action@v4
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: ./coverage
          disable_search: true
          fail_ci_if_error: true
