name: Coverage

on:
  push:
    branches:
      - 'develop'

jobs:
  check-src:
    runs-on: ubuntu-latest
    name: check if src files changed
    outputs:
      status: ${{ steps.changed-files.outputs.modified_files }}
    steps:
      - uses: actions/checkout@v4
      - uses: tj-actions/changed-files@v42
        id: changed-files
        with:
          files: |
            .github/actions/setup-build/action.yml
            .github/workflows/coverage.yml
            ./**/*.rs
            ./*.toml
            ./**/*.toml
            ./**/*.proto

  coverage:
    needs: check-src
    if: needs.check-src.outputs.status
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup
        uses: ./.github/actions/setup-build
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          os: ubuntu-latest
          toolchain: nightly

      - name: Install cargo-llvm-cov
        uses: taiki-e/install-action@cargo-llvm-cov

      - name: Generate code coverage for rust
        run: |
          python3 build.py cov

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v4
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: lcov.info
          fail_ci_if_error: true
