name: Coverage

on:
  push:
    branches:
      - 'develop'

env:
  RUSTFLAGS: "-Cinstrument-coverage"
  LLVM_PROFILE_FILE: "target/coverage/%p-%m.profraw"

jobs:
  check-src:
    runs-on: ubuntu-latest
    name: check if src files changed
    outputs:
      status: ${{ steps.changed-files.outputs.modified_files }}
    steps:
      - uses: actions/checkout@v4
      - uses: tj-actions/changed-files@v42
        id: changed-files
        with:
          files: |
            .github/actions/setup-build/action.yml
            .github/workflows/coverage.yml
            ./**/*.rs
            ./*.toml
            ./**/*.toml
            ./**/*.proto

  coverage:
    needs: check-src
    if: needs.check-src.outputs.status
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup
        uses: ./.github/actions/setup-build
        with:
          os: ubuntu-latest

      - name: Add components
        run: rustup component add llvm-tools
      - name: Install grcov
        run: cargo install grcov

      - name: Generate code coverage for rust
        run: |
          python3 build.py cov

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v4
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: ./coverage
          disable_search: true
          fail_ci_if_error: true
