name: pr

on:
  pull_request:
    branches: [ "main" ]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  changed-files:
    name: changed-files
    runs-on: ubuntu-latest
    outputs:
      src: ${{ steps.changed-files-yaml.outputs.src_any_changed }}
      miri: ${{ steps.changed-files-yaml.outputs.miri_any_changed }}
    steps:
      - uses: actions/checkout@v4
      - id: changed-files-yaml
        uses: tj-actions/changed-files@v44
        with:
          files_yaml: |
            src:
              - '**/*.rs'
              - '**/Cargo.toml'
            miri:
              - autd3-driver/Cargo.toml
              - autd3-driver/**/*.rs
              - autd3-firmware-emulator/Cargo.toml
              - autd3-firmware-emulator/**/*.rs
              - autd3-gain-holo/Cargo.toml
              - autd3-gain-holo/**/*.rs
              - autd3-link-soem/Cargo.toml
              - autd3-link-soem/**/*.rs
              - autd3-link-twincat/Cargo.toml
              - autd3-link-twincat/**/*.rs
              - autd3-protobuf/Cargo.toml
              - autd3-protobuf/**/*.rs

  test:
    needs: changed-files
    if: ${{ needs.changed-files.outputs.src == 'true' }}
    name: test-on-${{ matrix.os }}${{ matrix.arch && '-' }}${{ matrix.arch }}${{ matrix.features && '-' }}${{ matrix.features }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: windows-latest
            lint: true
          - os: ubuntu-latest
            lint: true
          - os: macos-latest
            lint: true
          - os: ubuntu-latest
            arch: arm32
            no-example: true
            no-test: true
          - os: ubuntu-latest
            arch: aarch64
            no-example: true
            no-test: true
          - os: windows-latest
            arch: aarch64
            no-test: true
          - os: ubuntu-latest
            features: "use_meter left_handed"
            lint: true
          - os: ubuntu-latest
            features: "lightweight async-trait"
            lint: true
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/setup-build
        with:
          os: ${{ matrix.os }}
          arch: ${{ matrix.arch }}
      - uses: taiki-e/install-action@v2
        with:
          tool: nextest
        if: ${{ matrix.no-test != true }}
      - run: python3 build.py build --arch "${{ matrix.arch }}" --features "${{ matrix.features }}" ${{ matrix.no-example && '--no-example' }}
      - run: python3 build.py test --features "${{ matrix.features }}"
        if: ${{ matrix.no-test != true }}
      - run: python3 build.py lint --features "${{ matrix.features }}" ${{ matrix.no-example && '--no-example' }}
        if: ${{ matrix.lint == true }}

  all-tests-passed:
    if: ${{ always() }}
    name: all-tests-passed
    runs-on: ubuntu-latest
    needs: test
    steps:
      - if: ${{ needs.test.result == 'failure' || needs.test.result == 'cancelled' }}
        run: exit 1

  miri:
    needs: changed-files
    if: ${{ needs.changed-files.outputs.miri == 'true' }}
    name: test-with-miri
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/setup-build
        with:
          os: ubuntu-latest
          toolchain: nightly
          components: miri
      - uses: taiki-e/install-action@v2
        with:
          tool: nextest
      - run: |
          python3 build.py test --miri

  auto-merge:
    needs:
      - all-tests-passed
      - miri
    permissions:
      pull-requests: write
      contents: write
    runs-on: ubuntu-latest
    if: ${{ always() && !cancelled() && !failure() && github.actor == 'dependabot[bot]' }}
    steps:
      - run: gh pr merge --rebase --auto "$PR_URL"
        env:
          PR_URL: ${{github.event.pull_request.html_url}}
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
