name: Release

on:
  push:
    tags:
    - 'v*'

defaults:
  run:
    shell: bash

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true
      - uses: actions-rust-lang/setup-rust-toolchain@v1
      - uses: obi1kenobi/cargo-semver-checks-action@v2
        with:
          feature-group: default-features
      - run: cargo publish --workspace --exclude autd3-examples --no-verify --token ${{ secrets.CRATEIO_TOKEN }}