name: Release

on:
  push:
    tags:
    - 'v*'

defaults:
  run:
    shell: bash

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true
      - uses: obi1kenobi/cargo-semver-checks-action@v2
        with:
          feature-group: default-features
          features: asynckkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkk,lkkk
      - run: |
          cd autd3-derive
          cargo publish --no-verify --token ${{ secrets.CRATEIO_TOKEN }}
          cd .. && sleep 15
          
          cd autd3-core
          cargo publish --no-verify --token ${{ secrets.CRATEIO_TOKEN }}
          cd .. && sleep 15

          cd autd3-driver
          cargo publish --no-verify --token ${{ secrets.CRATEIO_TOKEN }}
          cd .. && sleep 15

          cd autd3-firmware-emulator          
          cargo publish --no-verify --token ${{ secrets.CRATEIO_TOKEN }}
          cd .. && sleep 15

          cd autd3
          cargo publish --no-verify --token ${{ secrets.CRATEIO_TOKEN }}
          cd ..

          cd autd3-gain-holo          
          cargo publish --no-verify --token ${{ secrets.CRATEIO_TOKEN }}
          cd .. && sleep 15

          cd autd3-protobuf
          cargo publish --no-verify --token ${{ secrets.CRATEIO_TOKEN }}
          cd ..

          cd autd3-link-twincat
          cargo publish --no-verify --token ${{ secrets.CRATEIO_TOKEN }}
          cd ..

          cd autd3-link-simulator
          cargo publish --no-verify --token ${{ secrets.CRATEIO_TOKEN }}
          cd ..

          cd autd3-modulation-audio-file
          cargo publish --no-verify --token ${{ secrets.CRATEIO_TOKEN }}
