name: Release

on:
  push:
    tags:
    - 'v*'

jobs:
  build:
    name: publish-src
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup
        uses: ./.github/actions/setup-build
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          os: ubuntu-latest
      - name: Update submodules
        run: |
          git submodule update --init --recursive
      - name: Install Protoc
        uses: arduino/setup-protoc@v3
        with:
          repo-token: ${{ inputs.github-token }}
      - name: Check semver
        uses: obi1kenobi/cargo-semver-checks-action@v2
      - name: publish to carate.io
        run: |
          cd autd3-driver
          cargo publish --no-verify --dry-run
          cargo publish --no-verify --token ${{ secrets.CRATEIO_TOKEN }} || true
          cd .. && sleep 15
          cd autd3-derive
          cargo publish --no-verify --dry-run
          cargo publish --no-verify --token ${{ secrets.CRATEIO_TOKEN }} || true
          cd .. && sleep 15
          cd autd3-firmware-emulator
          cargo publish --no-verify --dry-run
          cargo publish --no-verify --token ${{ secrets.CRATEIO_TOKEN }} || true
          cd .. && sleep 15
          cd autd3
          cargo publish --no-verify --dry-run
          cargo publish --no-verify --token ${{ secrets.CRATEIO_TOKEN }} || true
          cd ..
          cd autd3-gain-holo
          cargo publish --no-verify --dry-run
          cargo publish --no-verify --token ${{ secrets.CRATEIO_TOKEN }} || true
          cd .. && sleep 15
          cd autd3-protobuf
          cargo publish --no-verify --dry-run
          cargo publish --no-verify --token ${{ secrets.CRATEIO_TOKEN }} || true
          cd ..
          cd autd3-link-soem
          cargo publish --no-verify --dry-run
          cargo publish --no-verify --token ${{ secrets.CRATEIO_TOKEN }} || true
          cd ..
          cd autd3-link-twincat
          cargo publish --no-verify --dry-run
          cargo publish --no-verify --token ${{ secrets.CRATEIO_TOKEN }} || true
          cd ..
          cd autd3-link-simulator
          cargo publish --no-verify --dry-run
          cargo publish --no-verify --token ${{ secrets.CRATEIO_TOKEN }} || true
          cd ..
          cd autd3-modulation-audio-file
          cargo publish --no-verify --dry-run
          cargo publish --no-verify --token ${{ secrets.CRATEIO_TOKEN }} || true
